import HomeView from '../views/_component_/HomeView.vue'

export default [
  {
    path: '/home',
    name: 'ComponentHome',
    label: 'Home',
    component: HomeView,
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/cards',
    name: 'Cards',
    label: 'Cards',
    component: () => import('../views/_component_/CardView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/buttons',
    name: 'Buttons',
    label: 'Buttons',
    component: () => import('../views/_component_/ButtonView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/dropdown',
    name: 'Dropdowns',
    label: 'Dropdowns',
    component: () => import('../views/_component_/DropdownView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/tooltip',
    name: 'Tooltips',
    label: 'Tooltips',
    component: () => import('../views/_component_/TooltipView.vue'),
    meta: { layout: 'Dashboard', test: 'sad' },
  },
  {
    path: '/tabs',
    name: 'Tabs',
    label: 'Tabs',
    component: () => import('../views/_component_/TabView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/steps',
    name: 'Stepper',
    label: 'Stepper',
    component: () => import('../views/_component_/StepperView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/modal',
    name: 'Modals',
    label: 'Modals',
    component: () => import('../views/_component_/ModalView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/pagination',
    name: 'Pagination',
    label: 'Paginations',
    component: () => import('../views/_component_/PaginationView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/table',
    name: 'Table',
    label: 'Tables',
    component: () => import('../views/_component_/TableView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form',
    name: 'Form',
    label: 'Form Validation',
    component: () => import('../views/_component_/FormView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form/input',
    name: 'FormInput',
    label: 'Form Input & Text Area',
    component: () => import('../views/_component_/FormInputView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form/select',
    name: 'FormSelect',
    label: 'Form Select',
    component: () => import('../views/_component_/FormSelectview.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form/checkbox-radio',
    name: 'FormCheckboxRadio',
    label: 'Form Checkbox & Radio',
    component: () => import('../views/_component_/FormCheckboxRadioView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form/file-upload',
    name: 'FormFileUpload',
    label: 'Form File Upload',
    component: () => import('../views/_component_/FormFileView.vue'),
    meta: { layout: 'Dashboard' },
  },
  {
    path: '/form/date-picker',
    name: 'FormDatePicker',
    label: 'Form Date Picker',
    component: () => import('../views/_component_/CalendarView.vue'),
    meta: { layout: 'Dashboard' },
  },
  // {
  //   path: '/sanbox',
  //   name: 'Sandbox',
  //   label: 'Component Dump',
  //   component: () => import('../views/_component_/SandboxView.vue'),
  //   meta: { layout: 'Dashboard' },
  // }
]